default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: receptor_app_development

test:
  <<: *default
  database: receptor_app_test

production:
  <<: *default
  database: receptor_app_production
  username: receptor_app
  password: <%= ENV["RECEPTOR_APP_DATABASE_PASSWORD"] %>
